### ISSUE TITLE
Moving over HTML5 Canvas Binding to use jsbind

### ISSUE THREAD

**Issue by define-private-public** [yglukhov/jsbind#3] opened 2017-01-13 01:36 UTC
Thanks for telling me about this repo.

Do you think it might be beneficial to move over this repo:
https://github.com/define-private-public/HTML5-Canvas-Nim

To use `jsbind`?  I wasn't really thinking about the emscripten target.

Also, what about a type's fields?  I didn't see anything about that in the example code.  Might there be any issues when dealing with procs like this: https://github.com/define-private-public/HTML5-Canvas-Nim/blob/master/lib/CanvasRenderingContext2D.nim#L40

**Comment by yglukhov** [comment] 2017-01-13 07:59
> Do you think it might be beneficial to move over this repo

That only depends on your will to support emscripten target =)

> Also, what about a type's fields? I didn't see anything about that in the example code. Might there be any issues when dealing with procs like this: https://github.com/define-private-public/HTML5-Canvas-Nim/blob/master/lib/CanvasRenderingContext2D.nim#L40

```nim
import jsbind
type
  CanvasRenderingContext2D* = ref object of JSObj

proc `fillStyle=`*(ctx: CanvasRenderingContext2D; color: cstring) {.jsimportProp.}
proc `fillStyle=`*(ctx: CanvasRenderingContext2D; gradient: CanvasGradient) {.jsimportProp.}
# etc...
```

**Comment by define-private-public** [comment] 2017-01-13 22:46
Yeah, I have no issue with supporting emscripten.  Is there any extra difficulty with it?  I haven't played around with emscripten that much.

**Comment by yglukhov** [comment] 2017-09-04 10:20
Well there's no difficulty except you have to have emscripten installed, and build configured appropriately =). I'm closing this, since it's not a bug.

**Closed as completed by yglukhov** 2017-09-04 10:20 UTC
